spring:
  main:
    web-application-type: none
  application:
    name: feign-client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
